server {
    listen 80;
    server_name server_nginx_ip (optional)domain_(optional)certificated;

    access_log /var/log/nginx-logs/wiki_access.log;
    error_log /var/log/nginx-logs/wiki_error.log;

    # Serve content directly from: /mnt/s3-wiki/Formacion/
    location / {
        alias /mnt/s3-wiki/Formacion/;

        # Serve only files .mp4 (ignoring cappital or none letters)
        location ~* \.mp4$ {
            types { video/mp4 mp4; }
            add_header Accept-Ranges bytes;
            try_files $uri $uri/ =404;
            sendfile on;
            tcp_nopush on;
            directio 8m;
           # output_buffers 1 512k;
        }

        # Block anything is not .mp4
        location ~* \.(?!mp4$).* {
            return 403;
        }
    }

    error_page 404 = @empty;
    location @empty {
        return 204;
    }
}
